from django import forms

class RecordForm(forms.Form):
    customerID =forms.CharField(label='customerID',max_length=100)
    gender=forms.CharField(label='gender',max_length=100)
    SeniorCitizen=forms.IntegerField(label='SeniorCitizen')
    Partner=forms.CharField(label='Partner',max_length=100)
    Dependents=forms.CharField(label='Dependents',max_length=100)
    tenure=forms.IntegerField(label='tenure')
    PhoneService=forms.CharField(label='PhoneService',max_length=100)
    MultipleLines=forms.CharField(label='MultipleLines',max_length=100)
    InternetService=forms.CharField(label='InternetService',max_length=100)
    OnlineSecurity=forms.CharField(label='OnlineSecurity',max_length=100)
    OnlineBackup=forms.CharField(label='OnlineBackup',max_length=100)
    DeviceProtection=forms.CharField(label='DeviceProtection',max_length=100)
    TechSupport=forms.CharField(label='TechSupport',max_length=100)
    StreamingTV=forms.CharField(label='StreamingTV',max_length=100)
    StreamingMovies=forms.CharField(label='StreamingMovies',max_length=100)
    Contract=forms.CharField(label='Contract',max_length=100)
    PaperlessBilling=forms.CharField(label='PaperlessBilling',max_length=100)
    PaymentMethod=forms.CharField(label='PaymentMethod',max_length=100)
    MonthlyCharges=forms.IntegerField(label='MonthlyCharges')
    TotalCharges=forms.IntegerField(label='TotalCharges')
    Churn=forms.CharField(label='Churn',max_length=100)
